### ISSUE TITLE
KNOW_TRANSITS parameter: intransit array

### ISSUE THREAD

**Issue by LuisCerdenoMota** [PlanetHunters/tkmatrix#18]
not null KNOW_TRANSITS parameter causes intrasit array always be true and time and flux change to empty arrays.

user-properties.yaml:
TARGET: "TIC 220513363"
SECTORS: [2]
MIN_PERIOD: 15 #DAYS
MAX_PERIOD: 15 #DAYS
STEP_PERIOD: 1 #DAYS
MIN_RADIUS: 5  #R_EARTH
MAX_RADIUS: 5  #R_EARTH
STEP_RADIUS: 1 #R_EARTH
EXPOSURE_TIME: 120 #SEC
PHASES: 1
DETREND_WS: 0.5
CPUS: 7
SHERLOCK_DEEPNESS: 0
SNR_THRESHOLD: 5
FIT_METHOD: 'tls'
KNOWN_TRANSITS:
  - P: 0.5
    T0: 1355.55
    D: 2.55
  - P: 3
    T0: 1360.14
    D: 3

**Comment by martindevora** [comment]
As this is delegated to lcbuilder now, we can close the issue.
