### ISSUE TITLE
Possible bug while running matrix_properties.yaml example

### ISSUE THREAD

**Issue by toribonidie** [PlanetHunters/tkmatrix#27]
Hi! I am interested in using your package for my own research, and I've been going through the examples to learn it, but I've come across an error message while trying to execute the line: `python3.8 -m tkmatrix --properties matrix_properties.yaml`, which you included in your `TOI-2257 I&R with multiphase analysis` notebook. Running this line does generate the TIC198485881_ir folder, containing the files aperatures.yaml, lc.csv, matrix.log, params_star.csv, and the folder tpfs with all of the fits files within it, but it generates the error message, `ValueError: could not broadcast input array from shape (156879,) into shape ()`, and does not include the a_tls_report.csv or inj-rec.pdf files. 

Thank you, I look forward to hearing back from you!

**Comment by toribonidie** [comment]
Thank you so much for the help and the quick response! I'll have to try it again tomorrow. I will let you know if there are any other issues.

Thanks!

**Comment by toribonidie** [comment]
Hi!

I am still having trouble with running `python3.8 -m tkmatrix --properties matrix_properties.yaml`. I am no longer receiving error messages, but it has been taking extremely long to run. I am running it on a 24x7 server with 40 CPUs, and after running it for 4 days, the a_tls_report.csv file only contains 100 rows. I created a new .yaml file with only 1 step in radius and period, and it took roughy an hour to complete (and the inj-rec.png is blank). I am not sure why it's going astronomically slow, and I am wondering how long it typically takes you and if there is anything you recommend!

Thank you so much!

**Comment by martindevora** [comment]
Hello.

The duration of the i&r task depends on very factors:

* The length of the light curve.
* The timespan of the light curve.
* The size of the star
* The OVERSAMPLING factor that you have selected.
* The size of your scenario (number of periods, number of radii and number of phases).

Some analysis took to us even one month in a 80 cores machine. Our recovery procedure is mainly based in the usage of Transit Least Squares, so we are completely dependent on the period grid size given by the star duty cycle and the timespan of the curve.

It might be of help if you could provide the `properties.yaml` content that you used to launch MATRIX. If you are using the TOI-2257 example you could:

```
TARGET: "TIC 198485881"
SECTORS: all  # Change the sectors to use only one as an example
EXPOSURE_TIME: 120
MIN_PERIOD: 1
MAX_PERIOD: 30
STEPS_PERIOD: 29 # Reduce this value
MIN_RADIUS: 0.5
MAX_RADIUS: 3.5
STEPS_RADIUS: 15
PHASES: 4 # Reduce this value. If you reduced it to 1, your scenarios would only be the size of STEPS_PERIOD * STEPS_RADIUS
DETREND_WS: 0.5
CPUS: 40
KNOWN_TRANSITS:
  - P: 35.1885
    T0: 1691.275171
    D: 1.9
OVERSAMPLING: 3 #The default value in MATRIX is 3, but you could change it to 1 and your period grids will be substantially reduced
```

I think that I will change the default `OVERSAMPLING` value to 1 for the next version of MATRIX.

If you are also interested, we already added an experimental module to trigger i&r for Radial Velocities data (and this module is much faster than the transits one).

Regards.

EDIT 1: Also, when you are only trying one scenario, as you did for your trials, it is going to show a useless and probably buggy plot. Anyhow, you can always create your own plot from the final `csv` file. 
EDIT 2: I should probably document this in the documentation.

**Comment by toribonidie** [comment]
Thank you so much! This clears things up! I was able to finish a practice run with just one sector very quickly. This will help me a lot 👍

**Comment by martindevora** [comment]
Glad to be of help. Please do not hesitate to ask again or give further feedback about the tool, that will be very useful.

Regards.

**Comment by martindevora** [comment]
I will close this issue as your question was resolved. Regards.
