### ISSUE TITLE
matrix snr and sde values 

### ISSUE THREAD

**Issue by toribonidie** [PlanetHunters/tkmatrix#30]
Hi Martin, 

As I am running my .yaml file with MATRIX (attached), I am noticing that all signals that are recovered have an SNR and SDE of 20 and 2000, respectively, and all signals that are not recovered do not provide and SNR and have an SDE of 0. 

I am wondering if this is a bug that you have also come across, or if these values are to be expected?

Thank you!

[KIC6923677.yaml.txt](https://github.com/PlanetHunters/tkmatrix/files/11536199/KIC6923677.yaml.txt)

**Comment by martindevora** [comment]
Hello Tori,
I'll take a look, but 20 and 2000 are typically values for orbits within the Roche Limit. SNR and SDE of 0 are weird reports, I will try to reproduce it.

**Comment by toribonidie** [comment]
Great, thank you.

**Comment by martindevora** [comment]
Can you please provide the csv report? That way I can try reproduce specific scenarios as your grid is very dense.

**Comment by toribonidie** [comment]
Sure! MATRIX is still running the file I attached in my first message, so I don't have the full csv report for it yet. However, I have had this issue with other runs so I am attaching a different yaml file (same star, less dense grid) and its corresponding csv report. 
[KIC6923677.txt](https://github.com/PlanetHunters/tkmatrix/files/11536440/KIC6923677.txt)
[a_tls_report.csv](https://github.com/PlanetHunters/tkmatrix/files/11536441/a_tls_report.csv)

Thanks so much!

**Comment by martindevora** [comment]
Hello, do you know what verison of MATRIX you are running?
`python3 -m pip show tkmatrix`

I am trying to reproduce this and the tls_report contains proper SNR and SDEs for the scenarios where you are finding 0s and empties.

**Comment by toribonidie** [comment]
I am using Version: 0.5.2

**Comment by martindevora** [comment]
I'd suggest to use the newest version of MATRIX, which is 0.6.2. Don't know if it will fix your issues, though. You can try installing it taking into account that it needs python >= 3.9. You can use this properties to test it quickly (it is basically your properties file with a very simplified scenarios grid):

```
TARGET: "KIC 6923677"
SECTORS: all
EXPOSURE_TIME: 1800
MIN_PERIOD: 3
MAX_PERIOD: 8
STEPS_PERIOD: 2
MIN_RADIUS: 7
MAX_RADIUS: 14
STEPS_RADIUS: 2
PHASES: 4
DETREND_WS: 1.0
DETRENDS_NUMBER: 12
DETREND_METHOD: 'biweight'
run_limit: 3
CPUS: 6
OVERSAMPLING: 5
STAR:
  "KIC 6923677":
    MASS: 2.048
    MASS_LOWER_ERROR: 0.065
    MASS_UPPER_ERROR: 0.065
    RADIUS: 10.619
    RADIUS_LOWER_ERROR: 0.017
    RADIUS_UPPER_ERROR: 0.017
    TEFF: 4967.6
    LOGG: 1
    LUM: 1
    LD_COEFFICIENTS: [0.4307,0.2796]

**Comment by martindevora** [comment]
I roughly calculated the depth of your biggest target (R=14R_earth) and it'd be something close to 174 ppms (correct me if I'm wrong). It seems really complicated to be able to spot something like that in such a star, whose RMS would be around 1000 ppms. It should not be impossible if we were lucky, though. Let's see.

**Comment by toribonidie** [comment]
Hi Martin,

Sorry for the delayed response. I haven't been able to upgrade to the latest version of MATRIX on the cluster I've been using for the past few months, and I naively uninstalled the current version before attempting to do so, so I have not had a working version of MATRIX for the past 2 weeks. Hopefully I will have an update for you soon.

As for your previous comment, I was also doubtful about being able to spot planets around these stars,  but I ran injection and recovery tests on some non-variable red clump stars and the results show that short-period hot jupiters are detectable. So I am hopeful.

I also wanted to let you know that I am presenting preliminary results at a conference in 2 weeks and am including you as a co author on my poster. Please email me at VEB19@pitt.edu if you have any questions about that.

Thank you for all of the help!
