### ISSUE TITLE
using 'bls' instead of 'tls'

### ISSUE THREAD

**Issue by toribonidie** [PlanetHunters/tkmatrix#32]
Hi!

It looks like tls is still being used when I include the line `TRANSIT_TEMPLATE: 'bls'` in my yaml file.

**Comment by martindevora** [comment]
Hello, the right property to use in MATRIX is `FIT_METHOD`. Sorry for the confusion (in terms of difference with SHERLOCK). You can inspect the properties file here https://github.com/PlanetHunters/tkmatrix/blob/master/tkmatrix/properties.yaml
