### ISSUE TITLE
Dockerfile for Matrix?

### ISSUE THREAD

**Issue by MichaelW-B** [PlanetHunters/tkmatrix#33]
Using SHERLOCK and MATRIX together: given that a dockerfile exists for SHERLOCK, it would be excellent, for use of both, if there was also a dockerfile for MATRIX, but ideally extending the one from SHERLOCK both for convenience and also helpful in then together not taking up so much more disk space.

**Comment by martindevora** [comment]
hello, a new docker image is now available in https://hub.docker.com/repository/docker/sherlockpipe/tkmatrix/general and it extends from the sherlock one
